accepted = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "GPL-3.0",
    "CC-BY-SA-4.0",
    "Unicode-DFS-2016",
    "Zlib",
    "MPL-2.0",
    "ISC",
    "Ubuntu-font-1.0",
    "OFL-1.1",
]
