[["Level 0"]]
coord = [0, 0]
tile_type = "Finish"
transform = "Id"
offset = 0

[["Level 1"]]
coord = [6, 5]
tile_type = "Turn"
transform = "Id"
offset = 0

[["Level 1"]]
coord = [5, 6]
tile_type = "Straight"
transform = "Rot180"
offset = 0

[["Level 1"]]
coord = [5, 7]
tile_type = "Turn"
transform = "Rot180"
offset = 0

[["Level 1"]]
coord = [6, 6]
tile_type = "Finish"
transform = "Id"
offset = 0

[["Level 1"]]
coord = [5, 5]
tile_type = "Turn"
transform = "Rot270"
offset = 0

[["Level 1"]]
coord = [6, 7]
tile_type = "Turn"
transform = "Rot90"
offset = 0

[["Level 2"]]
coord = [-1, 1]
tile_type = "Turn"
transform = "Rot90"
offset = 0

[["Level 2"]]
coord = [-2, -1]
tile_type = "Turn"
transform = "Rot270"
offset = 0

[["Level 2"]]
coord = [-1, 0]
tile_type = "Finish"
transform = "Id"
offset = 0

[["Level 2"]]
coord = [-2, 1]
tile_type = "Turn"
transform = "Rot180"
offset = 0

[["Level 2"]]
coord = [-1, -1]
tile_type = "LightTurns"
transform = "Id"
offset = 1

[["Level 2"]]
coord = [-2, 0]
tile_type = "Straight"
transform = "Rot180"
offset = 0

[["Level 3"]]
coord = [0, -1]
tile_type = "LightTurns"
transform = "Id"
offset = 0

[["Level 3"]]
coord = [0, 2]
tile_type = "Turn"
transform = "Flip135"
offset = 0

[["Level 3"]]
coord = [1, -1]
tile_type = "Turn"
transform = "Flip45"
offset = 0

[["Level 3"]]
coord = [1, 0]
tile_type = "Straight"
transform = "Rot180"
offset = 0

[["Level 3"]]
coord = [0, 0]
tile_type = "Finish"
transform = "Id"
offset = 0

[["Level 3"]]
coord = [1, 1]
tile_type = "Straight"
transform = "Rot180"
offset = 0

[["Level 3"]]
coord = [-1, -1]
tile_type = "Turn"
transform = "Rot270"
offset = 0

[["Level 3"]]
coord = [-1, 0]
tile_type = "Straight"
transform = "Rot180"
offset = 0

[["Level 3"]]
coord = [0, 1]
tile_type = "Merge"
transform = "Flip0"
offset = 0

[["Level 3"]]
coord = [1, 2]
tile_type = "Turn"
transform = "Flip90"
offset = 0

[["Level 3"]]
coord = [-1, 1]
tile_type = "Turn"
transform = "Rot180"
offset = 0

[["Level 4"]]
coord = [0, 0]
tile_type = "Finish"
transform = "Id"
offset = 0

[["Level 4"]]
coord = [-1, 0]
tile_type = "LightForwardTurn"
transform = "Flip90"
offset = 1

[["Level 4"]]
coord = [-1, -2]
tile_type = "Turn"
transform = "Flip45"
offset = 0

[["Level 4"]]
coord = [0, 1]
tile_type = "Turn"
transform = "Rot90"
offset = 0

[["Level 4"]]
coord = [-2, -2]
tile_type = "Turn"
transform = "Flip0"
offset = 0

[["Level 4"]]
coord = [-1, 1]
tile_type = "Turn"
transform = "Rot180"
offset = 0

[["Level 4"]]
coord = [0, -1]
tile_type = "LightForwardTurn"
transform = "Id"
offset = 1

[["Level 4"]]
coord = [-1, -1]
tile_type = "YieldIntersection"
transform = "Flip90"
offset = 0

[["Level 4"]]
coord = [-2, -1]
tile_type = "Turn"
transform = "Flip135"
offset = 0

[["Level 5"]]
coord = [-3, 0]
tile_type = "Turn"
transform = "Rot180"
offset = 0

[["Level 5"]]
coord = [-1, -1]
tile_type = "LightIntersection"
transform = "Id"
offset = 0

[["Level 5"]]
coord = [-2, -1]
tile_type = "YieldIntersection"
transform = "Id"
offset = 0

[["Level 5"]]
coord = [-2, -2]
tile_type = "LightTurns"
transform = "Flip0"
offset = 0

[["Level 5"]]
coord = [1, -1]
tile_type = "Turn"
transform = "Flip90"
offset = 0

[["Level 5"]]
coord = [0, -1]
tile_type = "Finish"
transform = "Rot270"
offset = 0

[["Level 5"]]
coord = [-3, -1]
tile_type = "Turn"
transform = "Rot270"
offset = 0

[["Level 5"]]
coord = [-2, 0]
tile_type = "Turn"
transform = "Rot90"
offset = 0

[["Level 5"]]
coord = [-1, -2]
tile_type = "Straight"
transform = "Rot90"
offset = 0

[["Level 5"]]
coord = [1, -2]
tile_type = "Turn"
transform = "Flip45"
offset = 0

[["Level 5"]]
coord = [0, -2]
tile_type = "Straight"
transform = "Rot90"
offset = 0

[["Level 6"]]
coord = [0, 1]
tile_type = "Straight"
transform = "Rot180"
offset = 0

[["Level 6"]]
coord = [0, 0]
tile_type = "Straight"
transform = "Rot180"
offset = 0

[["Level 6"]]
coord = [-1, -1]
tile_type = "Turn"
transform = "Flip0"
offset = 0

[["Level 6"]]
coord = [-1, 0]
tile_type = "LightIntersection"
transform = "Id"
offset = 0

[["Level 6"]]
coord = [-1, 3]
tile_type = "Turn"
transform = "Flip135"
offset = 0

[["Level 6"]]
coord = [0, 2]
tile_type = "Merge"
transform = "Rot180"
offset = 0

[["Level 6"]]
coord = [0, -1]
tile_type = "Turn"
transform = "Flip45"
offset = 0

[["Level 6"]]
coord = [0, 3]
tile_type = "Turn"
transform = "Flip90"
offset = 0

[["Level 6"]]
coord = [-1, 1]
tile_type = "Finish"
transform = "Id"
offset = 0

[["Level 6"]]
coord = [-1, 2]
tile_type = "LightForwardTurn"
transform = "Flip0"
offset = 1

[["Level 7"]]
coord = [-4, 2]
tile_type = "LightIntersection"
transform = "Rot180"
offset = 0

[["Level 7"]]
coord = [-5, 2]
tile_type = "Turn"
transform = "Rot180"
offset = 0

[["Level 7"]]
coord = [-2, 0]
tile_type = "LightForwardTurn"
transform = "Id"
offset = 1

[["Level 7"]]
coord = [-3, 0]
tile_type = "LightIntersection"
transform = "Rot270"
offset = 0

[["Level 7"]]
coord = [-4, 0]
tile_type = "YieldIntersection"
transform = "Rot270"
offset = 0

[["Level 7"]]
coord = [-3, 3]
tile_type = "Turn"
transform = "Rot90"
offset = 0

[["Level 7"]]
coord = [-5, 0]
tile_type = "LightForwardTurn"
transform = "Rot270"
offset = 0

[["Level 7"]]
coord = [-4, 3]
tile_type = "Turn"
transform = "Rot180"
offset = 0

[["Level 7"]]
coord = [-2, 1]
tile_type = "Finish"
transform = "Id"
offset = 0

[["Level 7"]]
coord = [-4, 1]
tile_type = "LightForwardTurn"
transform = "Rot180"
offset = 0

[["Level 7"]]
coord = [-5, 1]
tile_type = "Straight"
transform = "Rot180"
offset = 0

[["Level 7"]]
coord = [-2, -1]
tile_type = "Turn"
transform = "Id"
offset = 0

[["Level 7"]]
coord = [-3, -1]
tile_type = "Straight"
transform = "Rot270"
offset = 0

[["Level 7"]]
coord = [-2, 2]
tile_type = "Turn"
transform = "Rot90"
offset = 0

[["Level 7"]]
coord = [-4, -1]
tile_type = "Turn"
transform = "Rot270"
offset = 0

[["Level 7"]]
coord = [-3, 2]
tile_type = "Merge"
transform = "Rot90"
offset = 0

[["Level 8"]]
coord = [0, -2]
tile_type = "YieldIntersection"
transform = "Rot90"
offset = 0

[["Level 8"]]
coord = [1, -2]
tile_type = "LightForwardTurn"
transform = "Flip45"
offset = 1

[["Level 8"]]
coord = [1, -1]
tile_type = "Straight"
transform = "Rot180"
offset = 0

[["Level 8"]]
coord = [-1, 0]
tile_type = "Turn"
transform = "Flip135"
offset = 0

[["Level 8"]]
coord = [0, -1]
tile_type = "LightIntersection"
transform = "Id"
offset = 0

[["Level 8"]]
coord = [0, 0]
tile_type = "LightForwardTurn"
transform = "Id"
offset = 0

[["Level 8"]]
coord = [1, 1]
tile_type = "Turn"
transform = "Flip90"
offset = 0

[["Level 8"]]
coord = [0, 1]
tile_type = "Turn"
transform = "Flip135"
offset = 0

[["Level 8"]]
coord = [-1, -1]
tile_type = "Straight"
transform = "Id"
offset = 0

[["Level 8"]]
coord = [1, 0]
tile_type = "Finish"
transform = "Rot180"
offset = 0

[["Level 8"]]
coord = [-1, -2]
tile_type = "Turn"
transform = "Flip0"
offset = 0

[["Level 9"]]
coord = [0, -4]
tile_type = "Turn"
transform = "Rot90"
offset = 0

[["Level 9"]]
coord = [1, -3]
tile_type = "Straight"
transform = "Rot180"
offset = 0

[["Level 9"]]
coord = [0, -2]
tile_type = "LightIntersection"
transform = "Id"
offset = 0

[["Level 9"]]
coord = [1, 0]
tile_type = "Turn"
transform = "Flip90"
offset = 0

[["Level 9"]]
coord = [1, -1]
tile_type = "Straight"
transform = "Rot180"
offset = 0

[["Level 9"]]
coord = [-1, -6]
tile_type = "Straight"
transform = "Rot90"
offset = 0

[["Level 9"]]
coord = [1, -4]
tile_type = "Straight"
transform = "Rot180"
offset = 0

[["Level 9"]]
coord = [1, -6]
tile_type = "Turn"
transform = "Flip45"
offset = 0

[["Level 9"]]
coord = [0, -5]
tile_type = "Turn"
transform = "Id"
offset = 0

[["Level 9"]]
coord = [0, -1]
tile_type = "LightForwardTurn"
transform = "Id"
offset = 0

[["Level 9"]]
coord = [-2, 1]
tile_type = "Turn"
transform = "Rot180"
offset = 0

[["Level 9"]]
coord = [-1, -1]
tile_type = "Turn"
transform = "Flip135"
offset = 0

[["Level 9"]]
coord = [-2, -4]
tile_type = "LightIntersection"
transform = "Id"
offset = 0

[["Level 9"]]
coord = [-1, -4]
tile_type = "Turn"
transform = "Flip0"
offset = 0

[["Level 9"]]
coord = [-2, 0]
tile_type = "Straight"
transform = "Rot180"
offset = 0

[["Level 9"]]
coord = [-1, -2]
tile_type = "Straight"
transform = "Id"
offset = 0

[["Level 9"]]
coord = [-2, -3]
tile_type = "LightTurns"
transform = "Rot270"
offset = 0

[["Level 9"]]
coord = [-1, 1]
tile_type = "Finish"
transform = "Rot90"
offset = 0

[["Level 9"]]
coord = [-1, -5]
tile_type = "LightIntersection"
transform = "Rot270"
offset = 1

[["Level 9"]]
coord = [1, -2]
tile_type = "Straight"
transform = "Rot180"
offset = 0

[["Level 9"]]
coord = [0, -3]
tile_type = "Turn"
transform = "Id"
offset = 0

[["Level 9"]]
coord = [-2, -2]
tile_type = "Straight"
transform = "Rot180"
offset = 0

[["Level 9"]]
coord = [-2, -5]
tile_type = "Merge"
transform = "Id"
offset = 0

[["Level 9"]]
coord = [1, -5]
tile_type = "Straight"
transform = "Rot180"
offset = 0

[["Level 9"]]
coord = [-2, -6]
tile_type = "Turn"
transform = "Flip0"
offset = 0

[["Level 9"]]
coord = [-1, -3]
tile_type = "YieldIntersection"
transform = "Flip135"
offset = 0

[["Level 9"]]
coord = [-2, -1]
tile_type = "Straight"
transform = "Rot180"
offset = 0

[["Level 9"]]
coord = [0, 1]
tile_type = "Turn"
transform = "Rot90"
offset = 0

[["Level 9"]]
coord = [0, -6]
tile_type = "Straight"
transform = "Rot90"
offset = 0

[["Level 9"]]
coord = [0, 0]
tile_type = "Merge"
transform = "Id"
offset = 0

[["Level 10"]]
coord = [0, 0]
tile_type = "Straight"
transform = "Rot270"
offset = 0

[["Level 10"]]
coord = [-6, -1]
tile_type = "Turn"
transform = "Flip0"
offset = 0

[["Level 10"]]
coord = [-1, 0]
tile_type = "Straight"
transform = "Rot270"
offset = 0

[["Level 10"]]
coord = [-2, 0]
tile_type = "LightIntersection"
transform = "Rot270"
offset = 0

[["Level 10"]]
coord = [-3, 0]
tile_type = "YieldIntersection"
transform = "Rot270"
offset = 0

[["Level 10"]]
coord = [2, 1]
tile_type = "Turn"
transform = "Flip45"
offset = 0

[["Level 10"]]
coord = [-4, 0]
tile_type = "LightForwardTurn"
transform = "Rot270"
offset = 0

[["Level 10"]]
coord = [1, 1]
tile_type = "YieldIntersection"
transform = "Rot90"
offset = 0

[["Level 10"]]
coord = [-5, 0]
tile_type = "Straight"
transform = "Rot270"
offset = 0

[["Level 10"]]
coord = [0, 1]
tile_type = "Finish"
transform = "Rot90"
offset = 0

[["Level 10"]]
coord = [-6, 0]
tile_type = "Turn"
transform = "Flip135"
offset = 0

[["Level 10"]]
coord = [-1, 1]
tile_type = "Straight"
transform = "Rot90"
offset = 0

[["Level 10"]]
coord = [-2, 1]
tile_type = "Straight"
transform = "Rot90"
offset = 0

[["Level 10"]]
coord = [-3, 1]
tile_type = "Turn"
transform = "Rot180"
offset = 0

[["Level 10"]]
coord = [2, 2]
tile_type = "Turn"
transform = "Flip90"
offset = 0

[["Level 10"]]
coord = [1, 2]
tile_type = "Turn"
transform = "Flip135"
offset = 0

[["Level 10"]]
coord = [-3, -1]
tile_type = "Turn"
transform = "Flip45"
offset = 0

[["Level 10"]]
coord = [-4, -1]
tile_type = "Straight"
transform = "Rot90"
offset = 0

[["Level 10"]]
coord = [1, 0]
tile_type = "Turn"
transform = "Id"
offset = 0

[["Level 10"]]
coord = [-5, -1]
tile_type = "Straight"
transform = "Rot90"
offset = 0

[["Level 11"]]
coord = [0, 0]
tile_type = "Turn"
transform = "Rot270"
offset = 0

[["Level 11"]]
coord = [-2, -3]
tile_type = "Turn"
transform = "Flip0"
offset = 0

[["Level 11"]]
coord = [3, -2]
tile_type = "YieldIntersection"
transform = "Flip90"
offset = 0

[["Level 11"]]
coord = [-1, 0]
tile_type = "LightIntersection"
transform = "Id"
offset = 0

[["Level 11"]]
coord = [1, -5]
tile_type = "Straight"
transform = "Id"
offset = 0

[["Level 11"]]
coord = [-2, 0]
tile_type = "Straight"
transform = "Id"
offset = 0

[["Level 11"]]
coord = [2, -2]
tile_type = "Turn"
transform = "Rot270"
offset = 0

[["Level 11"]]
coord = [3, -7]
tile_type = "Turn"
transform = "Flip45"
offset = 0

[["Level 11"]]
coord = [0, -2]
tile_type = "Straight"
transform = "Id"
offset = 0

[["Level 11"]]
coord = [2, -7]
tile_type = "Straight"
transform = "Rot90"
offset = 0

[["Level 11"]]
coord = [-1, -2]
tile_type = "Turn"
transform = "Id"
offset = 0

[["Level 11"]]
coord = [3, -4]
tile_type = "Straight"
transform = "Rot180"
offset = 0

[["Level 11"]]
coord = [1, -7]
tile_type = "Turn"
transform = "Flip0"
offset = 0

[["Level 11"]]
coord = [0, 1]
tile_type = "Finish"
transform = "Rot180"
offset = 0

[["Level 11"]]
coord = [4, -1]
tile_type = "Turn"
transform = "Rot90"
offset = 0

[["Level 11"]]
coord = [-2, -2]
tile_type = "Turn"
transform = "Flip135"
offset = 0

[["Level 11"]]
coord = [-1, 1]
tile_type = "LightForwardTurn"
transform = "Id"
offset = 0

[["Level 11"]]
coord = [3, -1]
tile_type = "YieldIntersection"
transform = "Rot180"
offset = 0

[["Level 11"]]
coord = [1, -4]
tile_type = "Straight"
transform = "Id"
offset = 0

[["Level 11"]]
coord = [2, -1]
tile_type = "Merge"
transform = "Flip45"
offset = 0

[["Level 11"]]
coord = [-2, 1]
tile_type = "Turn"
transform = "Flip135"
offset = 0

[["Level 11"]]
coord = [1, -1]
tile_type = "Straight"
transform = "Rot90"
offset = 0

[["Level 11"]]
coord = [3, -6]
tile_type = "Straight"
transform = "Rot180"
offset = 0

[["Level 11"]]
coord = [0, -1]
tile_type = "LightForwardTurn"
transform = "Rot90"
offset = 0

[["Level 11"]]
coord = [-1, -1]
tile_type = "YieldIntersection"
transform = "Rot90"
offset = 0

[["Level 11"]]
coord = [3, -3]
tile_type = "LightIntersection"
transform = "Rot180"
offset = 1

[["Level 11"]]
coord = [1, -6]
tile_type = "Straight"
transform = "Id"
offset = 0

[["Level 11"]]
coord = [0, 2]
tile_type = "Turn"
transform = "Flip90"
offset = 0

[["Level 11"]]
coord = [-2, -1]
tile_type = "Turn"
transform = "Flip0"
offset = 0

[["Level 11"]]
coord = [-1, 2]
tile_type = "Turn"
transform = "Flip135"
offset = 0

[["Level 11"]]
coord = [3, 0]
tile_type = "LightForwardTurn"
transform = "Flip90"
offset = 1

[["Level 11"]]
coord = [1, -3]
tile_type = "Turn"
transform = "Rot90"
offset = 0

[["Level 11"]]
coord = [2, 0]
tile_type = "Straight"
transform = "Rot270"
offset = 0

[["Level 11"]]
coord = [0, -3]
tile_type = "Merge"
transform = "Rot90"
offset = 0

[["Level 11"]]
coord = [1, 0]
tile_type = "Straight"
transform = "Rot270"
offset = 0

[["Level 11"]]
coord = [3, -5]
tile_type = "Straight"
transform = "Rot180"
offset = 0

[["Level 11"]]
coord = [-1, -3]
tile_type = "Straight"
transform = "Rot90"
offset = 0

[["Level 11"]]
coord = [4, -2]
tile_type = "Turn"
transform = "Id"
offset = 0
